[package]
name = "krungkualalumpur/sintesa"
version = "0.2.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Maid = "nightcycle/maid@1.1.1"
Fusion = "elttob/fusion@^0.1.1-beta"
ColdFusion8 = "nightcycle/cold-fusion@8.0.0"
