[package]
name = "nightcycle/queue"
description = "A basic queue"
version = "2.3.0"
authors = [ "CJ Oyer <coyer@nightcycle.us>",]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = [ "Packages", ".vscode",]

[dependencies]
Maid = "nightcycle/maid@1.1.4"
