[package]
name = "nightcycle/compression-util"
description = "Compress native Roblox types"
version = "4.1.1"
authors = ["CJ Oyer <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]

[dependencies]
HashUtil = "boatbomber/hashlib@1.0.0"
TestEZ = "roblox/testez@0.4.1"
TableUtil = "nightcycle/table-util@1.1.0"
